// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Slottet.Infrastructure.Data;

#nullable disable

namespace Slottet.Infrastructure.Migrations
{
    [DbContext(typeof(SlottetDBContext))]
    [Migration("20260514000000_RemoveStaffShiftAddDepartmentToShiftBoard")]
    partial class RemoveStaffShiftAddDepartmentToShiftBoard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Slottet.Domain.Entities.ShiftBoard", b =>
                {
                    b.Property<Guid>("ShiftBoardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftBoardID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("ShiftBoards");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ShiftBoard", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
