// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Slottet.Infrastructure.Data;

#nullable disable

namespace Slottet.Infrastructure.Migrations
{
    [DbContext(typeof(SlottetDBContext))]
    [Migration("20260512091315_SoftDeleteStaffHistoryLinks")]
    partial class SoftDeleteStaffHistoryLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("StaffID");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Slottet.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KeyValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PerformedAtTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PerformedByStaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerformedByStaffName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("AuditLogID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.DepartmentTask", b =>
                {
                    b.Property<Guid>("DepartmentTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentTaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentTaskID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("DepartmentTasks");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.GroceryDay", b =>
                {
                    b.Property<Guid>("GroceryDayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroceryDayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GroceryDayID");

                    b.ToTable("GroceryDays");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Medicine", b =>
                {
                    b.Property<Guid>("MedicineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MedicineGivenTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MedicineRegisteredTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MedicineTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ResidentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MedicineID");

                    b.HasIndex("ResidentID");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.PN", b =>
                {
                    b.Property<Guid>("PNID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PNGivenTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PNReason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("PNRegisteredTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ResidentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResidentStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PNID");

                    b.HasIndex("ResidentID");

                    b.HasIndex("ResidentStatusID");

                    b.ToTable("PNs");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("PaymentMethodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentMethodID");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Phone", b =>
                {
                    b.Property<Guid>("PhoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("ResidentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroceryDayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ResidentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ResidentID");

                    b.HasIndex("GroceryDayID");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ResidentPaymentMethod", b =>
                {
                    b.Property<Guid>("ResidentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentMethodID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResidentID", "PaymentMethodID");

                    b.HasIndex("PaymentMethodID");

                    b.ToTable("ResidentPaymentMethods");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ResidentStatus", b =>
                {
                    b.Property<Guid>("ResidentStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ResidentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RiskLevelID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResidentStatusID");

                    b.HasIndex("ResidentID");

                    b.HasIndex("RiskLevelID");

                    b.ToTable("ResidentStatuses");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.RiskLevel", b =>
                {
                    b.Property<Guid>("RiskLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RiskLevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RiskLevelID");

                    b.ToTable("RiskLevels");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ShiftBoard", b =>
                {
                    b.Property<Guid>("ShiftBoardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftBoardID");

                    b.ToTable("ShiftBoards");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.SpecialResponsibility", b =>
                {
                    b.Property<Guid>("SpecialResponsibilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecialResponsibilityID");

                    b.ToTable("SpecialResponsibilities");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.SpecialResponsibilityStaff", b =>
                {
                    b.Property<Guid>("SpecialResponsibilityStaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("SpecialResponsibilityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SpecialResponsibilityStaffID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("SpecialResponsibilityID");

                    b.HasIndex("StaffID");

                    b.ToTable("SpecialResponsibilityStaff", (string)null);
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StaffID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffPN", b =>
                {
                    b.Property<Guid>("StaffPNID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PNID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StaffPNID");

                    b.HasIndex("PNID");

                    b.HasIndex("StaffID");

                    b.ToTable("StaffPNs");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffPhone", b =>
                {
                    b.Property<Guid>("StaffPhoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PhoneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StaffPhoneID");

                    b.HasIndex("PhoneID");

                    b.HasIndex("StaffID");

                    b.ToTable("StaffPhones");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffResidentStatus", b =>
                {
                    b.Property<Guid>("StaffResidentStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ResidentStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StaffResidentStatusID");

                    b.HasIndex("ResidentStatusID");

                    b.HasIndex("StaffID");

                    b.ToTable("StaffResidentStatuses");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffShift", b =>
                {
                    b.Property<Guid>("StaffShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ShiftBoardID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StaffShiftID");

                    b.HasIndex("ShiftBoardID");

                    b.HasIndex("StaffID");

                    b.ToTable("StaffShifts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffID");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.DepartmentTask", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Department", "Department")
                        .WithMany("DepartmentTasks")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Medicine", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Resident", "Resident")
                        .WithMany("Medicines")
                        .HasForeignKey("ResidentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.PN", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Resident", "Resident")
                        .WithMany("PNs")
                        .HasForeignKey("ResidentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.ResidentStatus", null)
                        .WithMany("PNs")
                        .HasForeignKey("ResidentStatusID");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Phone", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Department", "Department")
                        .WithMany("Phones")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Resident", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.GroceryDay", "GroceryDay")
                        .WithMany("Residents")
                        .HasForeignKey("GroceryDayID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroceryDay");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ResidentPaymentMethod", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("ResidentPaymentMethods")
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.Resident", "Resident")
                        .WithMany("ResidentPaymentMethods")
                        .HasForeignKey("ResidentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ResidentStatus", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Resident", "Resident")
                        .WithMany("ResidentStatuses")
                        .HasForeignKey("ResidentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.RiskLevel", "RiskLevel")
                        .WithMany("ResidentStatuses")
                        .HasForeignKey("RiskLevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("RiskLevel");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.SpecialResponsibilityStaff", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.SpecialResponsibility", "SpecialResponsibility")
                        .WithMany("SpecialResponsibilityStaffs")
                        .HasForeignKey("SpecialResponsibilityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("SpecialResponsibility");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Staff", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Department", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffPN", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.PN", "PN")
                        .WithMany("StaffPNs")
                        .HasForeignKey("PNID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.Staff", "Staff")
                        .WithMany("StaffPNs")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PN");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffPhone", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Phone", "Phone")
                        .WithMany("StaffPhones")
                        .HasForeignKey("PhoneID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.Staff", "Staff")
                        .WithMany("StaffPhones")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Phone");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffResidentStatus", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.ResidentStatus", "ResidentStatus")
                        .WithMany("StaffResidentStatuses")
                        .HasForeignKey("ResidentStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.Staff", "Staff")
                        .WithMany("StaffResidentStatuses")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResidentStatus");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffShift", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.ShiftBoard", "ShiftBoard")
                        .WithMany("StaffShifts")
                        .HasForeignKey("ShiftBoardID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.Staff", "Staff")
                        .WithMany("StaffShifts")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ShiftBoard");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Department", b =>
                {
                    b.Navigation("DepartmentTasks");

                    b.Navigation("Phones");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.GroceryDay", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.PN", b =>
                {
                    b.Navigation("StaffPNs");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("ResidentPaymentMethods");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Phone", b =>
                {
                    b.Navigation("StaffPhones");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Resident", b =>
                {
                    b.Navigation("Medicines");

                    b.Navigation("PNs");

                    b.Navigation("ResidentPaymentMethods");

                    b.Navigation("ResidentStatuses");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ResidentStatus", b =>
                {
                    b.Navigation("PNs");

                    b.Navigation("StaffResidentStatuses");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.RiskLevel", b =>
                {
                    b.Navigation("ResidentStatuses");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ShiftBoard", b =>
                {
                    b.Navigation("StaffShifts");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.SpecialResponsibility", b =>
                {
                    b.Navigation("SpecialResponsibilityStaffs");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Staff", b =>
                {
                    b.Navigation("StaffPNs");

                    b.Navigation("StaffPhones");

                    b.Navigation("StaffResidentStatuses");

                    b.Navigation("StaffShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
