// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Slottet.Infrastructure.Data;

#nullable disable

namespace Slottet.Infrastructure.Migrations
{
    [DbContext(typeof(SlottetDBContext))]
    [Migration("20260425194803_Phone-Swapping-Feature")]
    partial class PhoneSwappingFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Slottet.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.DepartmentTask", b =>
                {
                    b.Property<Guid>("DepartmentTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentTaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentTaskID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("DepartmentTasks");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.GroceryDay", b =>
                {
                    b.Property<Guid>("GroceryDayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroceryDayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GroceryDayID");

                    b.ToTable("GroceryDays");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Medicine", b =>
                {
                    b.Property<Guid>("MedicineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MedicineGivenTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MedicineRegisteredTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MedicineTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ResidentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MedicineID");

                    b.HasIndex("ResidentID");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.PN", b =>
                {
                    b.Property<Guid>("PNID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PNStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("PNTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ResidentStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PNID");

                    b.HasIndex("ResidentStatusID");

                    b.ToTable("PNs");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("PaymentMethodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentMethodID");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Phone", b =>
                {
                    b.Property<Guid>("PhoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("ResidentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroceryDayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ResidentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ResidentID");

                    b.HasIndex("GroceryDayID");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ResidentPaymentMethod", b =>
                {
                    b.Property<Guid>("ResidentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentMethodID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResidentID", "PaymentMethodID");

                    b.HasIndex("PaymentMethodID");

                    b.ToTable("ResidentPaymentMethods");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ResidentStatus", b =>
                {
                    b.Property<Guid>("ResidentStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ResidentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RiskLevelID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResidentStatusID");

                    b.HasIndex("ResidentID");

                    b.HasIndex("RiskLevelID");

                    b.ToTable("ResidentStatuses");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.RiskLevel", b =>
                {
                    b.Property<Guid>("RiskLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RiskLevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RiskLevelID");

                    b.ToTable("RiskLevels");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ShiftBoard", b =>
                {
                    b.Property<Guid>("ShiftBoardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftBoardID");

                    b.ToTable("ShiftBoards");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.SpecialResponsibility", b =>
                {
                    b.Property<Guid>("SpecialResponsibilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftBoardID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecialResponsibilityID");

                    b.HasIndex("ShiftBoardID");

                    b.ToTable("SpecialResponsibilities");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StaffID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffPhone", b =>
                {
                    b.Property<Guid>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhoneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StaffID", "PhoneID", "AssignedAt");

                    b.HasIndex("PhoneID");

                    b.ToTable("StaffPhones");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffResidentStatus", b =>
                {
                    b.Property<Guid>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResidentStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StaffID", "ResidentStatusID");

                    b.HasIndex("ResidentStatusID");

                    b.ToTable("StaffResidentStatuses");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffShift", b =>
                {
                    b.Property<Guid>("ShiftBoardID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShiftBoardID", "StaffID");

                    b.HasIndex("StaffID");

                    b.ToTable("StaffShifts");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.DepartmentTask", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Department", "Department")
                        .WithMany("DepartmentTasks")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Medicine", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Resident", "Resident")
                        .WithMany("Medicines")
                        .HasForeignKey("ResidentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.PN", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.ResidentStatus", "ResidentStatus")
                        .WithMany("PNs")
                        .HasForeignKey("ResidentStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResidentStatus");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Phone", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Department", "Department")
                        .WithMany("Phones")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Resident", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.GroceryDay", "GroceryDay")
                        .WithMany("Residents")
                        .HasForeignKey("GroceryDayID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroceryDay");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ResidentPaymentMethod", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("ResidentPaymentMethods")
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.Resident", "Resident")
                        .WithMany("ResidentPaymentMethods")
                        .HasForeignKey("ResidentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ResidentStatus", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Resident", "Resident")
                        .WithMany("ResidentStatuses")
                        .HasForeignKey("ResidentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.RiskLevel", "RiskLevel")
                        .WithMany("ResidentStatuses")
                        .HasForeignKey("RiskLevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("RiskLevel");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.SpecialResponsibility", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.ShiftBoard", "ShiftBoard")
                        .WithMany("SpecialResponsibilities")
                        .HasForeignKey("ShiftBoardID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShiftBoard");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Staff", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Department", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffPhone", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.Phone", "Phone")
                        .WithMany("StaffPhones")
                        .HasForeignKey("PhoneID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.Staff", "Staff")
                        .WithMany("StaffPhones")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phone");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffResidentStatus", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.ResidentStatus", "ResidentStatus")
                        .WithMany("StaffResidentStatuses")
                        .HasForeignKey("ResidentStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.Staff", "Staff")
                        .WithMany("StaffResidentStatuses")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResidentStatus");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.StaffShift", b =>
                {
                    b.HasOne("Slottet.Domain.Entities.ShiftBoard", "ShiftBoard")
                        .WithMany("StaffShifts")
                        .HasForeignKey("ShiftBoardID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slottet.Domain.Entities.Staff", "Staff")
                        .WithMany("StaffShifts")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShiftBoard");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Department", b =>
                {
                    b.Navigation("DepartmentTasks");

                    b.Navigation("Phones");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.GroceryDay", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("ResidentPaymentMethods");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Phone", b =>
                {
                    b.Navigation("StaffPhones");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Resident", b =>
                {
                    b.Navigation("Medicines");

                    b.Navigation("ResidentPaymentMethods");

                    b.Navigation("ResidentStatuses");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ResidentStatus", b =>
                {
                    b.Navigation("PNs");

                    b.Navigation("StaffResidentStatuses");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.RiskLevel", b =>
                {
                    b.Navigation("ResidentStatuses");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.ShiftBoard", b =>
                {
                    b.Navigation("SpecialResponsibilities");

                    b.Navigation("StaffShifts");
                });

            modelBuilder.Entity("Slottet.Domain.Entities.Staff", b =>
                {
                    b.Navigation("StaffPhones");

                    b.Navigation("StaffResidentStatuses");

                    b.Navigation("StaffShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
